name: exit-prerelease

on: [push]

jobs:
  exit-prerelease:
    name: Exit Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    if: ${{ github.ref != 'refs/heads/dev'}}
    steps:
      - name: Create .npmrc
        run: echo ${JFROG_NPMRC_B64} | base64 -d >> .npmrc
        env:
          JFROG_NPMRC_B64: ${{ secrets.JFROG_NPMRC_B64 }}

      - run: npm ci

      - run: npm exec -- changeset pre exit

      - name: Remove .npmrc
        run: rm -rf .npmrc
